import Head from "next/head";
import Header from "../components/Header";

export default function Layout({ children }) {
  return (
    <div className="main-container">
      <Head>
        <title>Next.js FullStack Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container">{children}</div>
    </div>
  );
}
