import Head from "next/head";
import Header from "../components/Header";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session, status } = useSession();

  return (
    <div className="main-container">
      <Head>
        <title>Next.js FullStack Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container">
        {session ? (
          <div>
            Logged In User
            <pre>{JSON.stringify(session, null, 2)}</pre>
          </div>
        ) : (
          <div>Not Logged In</div>
        )}
      </div>
    </div>
  );
}
